### ISSUE TITLE
Getting Error AADSTS65001

### ISSUE THREAD

**Issue by godfreymakori** [TangentSolutions/PowerBI-SDK-PHP#1]
Error Message: The user or administrator has not consented to use the application with ID 'e3130-2*****' named 'XXXX'. Send an interactive authorization request for this user and resource. 

Kindly help

**Comment by geevcookie** [comment]
Did you follow all the steps listed at https://github.com/TangentSolutions/PowerBI-SDK-PHP/wiki/Get-An-Access-Token ? Specifically: https://github.com/TangentSolutions/PowerBI-SDK-PHP/wiki/PowerBI-App-Registration

**Comment by godfreymakori** [comment]
Yes, I followed the steps, I suspect am using a non-admin account to set it up. I'll share the fix once I figure it out. Thanks

**Comment by godfreymakori** [comment]
Got this sorted. Seems Microsoft had a technical issue on that day. Thanks.
