### ISSUE TITLE
Dataset Wikipage

### ISSUE THREAD

**Issue by cord** [TangentSolutions/PowerBI-SDK-PHP#15]
PHP7 .3.8

on

https://github.com/TangentSolutions/PowerBI-SDK-PHP/wiki/Dataset

it says

```$response = $this->client->getDatasets();```

which results in an error

`Call to undefined method Tngnt\PBI\Client::getDatasets()`

but

```$response = $this->client->dataset->getDatasets();```

works

**Comment by geevcookie** [comment]
Fixed. Thanks for the feedback!
