### ISSUE TITLE
is this still updated

### ISSUE THREAD

**Issue by developerside** [TangentSolutions/PowerBI-SDK-PHP#2]
is this still updated?

**Comment by tangentadmin** [comment]
Hi Chris,

It definitely is. Let us know if you have an issue.

Kind Regards,



[Tangent Solutions]<http://www.tangentsolutions.co.za/>



<http://www.tangentsolutions.co.za/>
GET /Ruaan Erasmus
{
        "role" : Architect
        "cell_number" : 078 719 6957
        "office" : 011 463 7844
        "web" : www.tangentsolutions.co.za
        "address" : Culross Court, 16 Culross Road, Bryanston, Johannesburg
}




On Mon, Nov 27, 2017 at 10:26 AM chris ann <chris ann <mailto:chris%20ann%20<notifications@github.com>> > wrote:

is this still updated?

**Comment by stephanvierkant** [comment]
This issue is still relevant. Issues and PR's don't get any response.

**Comment by geevcookie** [comment]
Its been a while, but yes... it's still active and I am back. :smile:
