### ISSUE TITLE
Install Power SDK-PHP

### ISSUE THREAD

**Issue by haibasky** [TangentSolutions/PowerBI-SDK-PHP#5]
Hi,
I tried to install the SDK file in my local system, but i unable to install, its shows the errors, any guide for installing SDK in local system and integrate Power BI API

**Comment by stephanvierkant** [comment]
What kind of errors? Same issue as #8?

**Comment by geevcookie** [comment]
Assuming this is stale now. Feel free to reopen if you are still experiencing issues. Apologies for the delay.
