### ISSUE TITLE
Installing SDK via composer Issue

### ISSUE THREAD

**Issue by edsonromerop** [TangentSolutions/PowerBI-SDK-PHP#8]
Hi, I have this problem installing the SDK using composer:

_[InvalidArgumentException]
  Could not find a version of package tangent-solutions/powerbi-sdk matching your minimum-stability (stable). Require
   it with an explicit version constraint allowing its desired stability._

What can I do to resolve this?

Thank you!

**Comment by weeix** [comment]
I had this problem too.

Solved by installing the SDK with this command instead:

    composer require "tangent-solutions/powerbi-sdk @dev"

**Comment by edsonromerop** [comment]
Catching up with my issues, solved, using @weeix solution. Thank you very much.
