### ISSUE TITLE
Sync issue

### ISSUE THREAD

**Issue by ketanvekariya** [TangentSolutions/PowerBI-SDK-PHP#9]
Hello Sir,

This is to inform you that sometime api result will be same unless and untill i reupload my file.

I checked permission of file but its fine.

**Comment by ketanvekariya** [comment]
Please provide me proper guidance

**Comment by geevcookie** [comment]
Assuming this is stale now. Feel free to reopen if you are still experiencing issues. Apologies for the delay.
